import { useSearchParams } from "react-router-dom";
import ApiClient from "../uitls/client-api";
import AppExtensionsSDK, { Command, Modal } from "@pipedrive/app-extensions-sdk";


// Redirect the user to the authorization URL generated by the client
export default function Callback() {
    console.log("recivied")
    const [searchParams, setSearchParams] = useSearchParams();
    const code = searchParams.get("code")

  return <div>lofff</div>
};


